### PR TITLE
support 'this' operator for arrays

### PR DESCRIPTION
**Pull request by YerkoPalma**
This is a litle feature added. Basically, allows to replace array using the `this` word, like this:

```js
pupa(' {this}', [1, 2, 3]);
// ' 1 2 3'
```

I added this feature, thinking on dynamic or user provided array of data, for instance to generate a html list, actually, you need to know the size of the array and have a template with the position of each item. With this change, you don't need this.

```js
// before
pupa('<li>{0}</li><li>{1}</li><li>{2}</li><li>{3}</li><li>{4}</li><li>{5}</li>', array) // and so on ...

// with this PR
pupa('<li>{this}</li>', array)
```

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sorry about the delay. I was back and forth on whether to accept this, but I've decided not to. It's just too magic and I want to keep this module explicit and simple.

If users need this, they can simply do:

```js
let result = '';
for (const x of array) {
	reuslt += pupa('<li>{0}</li>', [x]);
}
```

**Comment by YerkoPalma** [comment]
Fair enough, I though it could be a bit out of scope for this module.
Thanks for the response anyway :)

**Comment by sindresorhus** [comment]
If you really want this you could always just publish it under a different name ;)

**Comment by YerkoPalma** [comment]
Already done https://www.npmjs.com/package/@yerkopalma/pupa

**Pull request closed without merging**
