### PR TITLE
Added support for dot in data (Issue #17)

### LINKED ISSUE #17: Escape dot character
Hi  guys,
Sometimes, my data is an object that includes a `dot` character.

```js
pupa('The mobile number of {name} is {phone\.mobile}', {
    name: 'Sindre',
    "phone.mobile": "609 24 363"
});
```
Maybe should be supported  `\` character to escape the `dot` character.

### PR DESCRIPTION
**Pull request by j-a-h-i-r**
This PR implements the changes required for #17 

Summary of changes:
- Updated the braceRegexes to support escape (\) character
- Updated the template property split functionality to NOT split if the dot is escaped

Fixes #17

### CODE REVIEW

**Comment by sindresorhus** [comment]
This needs more tests. For example:

- `{user\\.phone\\.mobile}`
- `{user\\\.phone}` (double escape)

The escaping ability needs to be documented.

**Comment by j-a-h-i-r** [comment]
Thanks for the feedback. I'll come back with these changes ASAP!

**Comment by j-a-h-i-r** [comment]
What will be the expected result for double escape (`\\\`)?

```
'number: {user\\\.phone}' -> {'user\\.phone': '12345'}
//=> 'number: 12345'
```

Is this the expected behavior?

**Note:** Using `\\\` causes `xo` to show the following error

```
✖  34:40  Unnecessary escape character: \..  no-useless-escape
```

@sindresorhus

**Comment by j-a-h-i-r** [comment]
Meanwhile, I've updated the docs and added some more tests

**Comment by sindresorhus** [comment]
> Note: Using \\\ causes xo to show the following error

Maybe it should have been `\\\\`, I don't remember.

**Comment by sindresorhus** [comment]
I'm just paranoid that this change will introduce some kind of security vulnerability later on. That's why I am being very careful and asking for a lot of tests.

**Comment by sindresorhus** [comment]
I would still like to see more tests. Try to think of ways this new functionality could be abused.

**Comment by j-a-h-i-r** [comment]
I share your concern. I'll try to come up with some more tests. Thanks for the feedback!

**Review by sindresorhus — CHANGES_REQUESTED** [review]

**Comment by conartist6** [comment]
I took pupa and adapted it to a slightly different usage (which I'm calling rawr). The syntax is the same but I do different things with my braces. Anyway I wrote a proper parser (which I have not tested at all). It has full support for escaping and detects more edge cases. If you're interested here's what I've got: https://github.com/conartist6/errawr/blob/18e3ea33ad1a23004d7c15a07efb6bf4e94010e7/lib/rawr.ts

**Comment by conartist6** [comment]
Actually I think the biggest win would be if I removed the key validation regex entirely, at which point keys would be free to contain pretty much anything character aside from `{`, `}` or `\` or `.`. This would be a win as it would make the engine work for engineers coding in non-english languages.

**Comment by conartist6** [comment]
Ah but I haven't allowed `.` in keys to be escaped yet actually! Fixing these problems.

**Comment by conartist6** [comment]
Fixed in [49de2ab](https://github.com/conartist6/errawr/blob/49de2ab29b477f28ba102d154a50af79b974e5fe/lib/rawr.ts)

**Comment by conartist6** [comment]
I have opened [an alternative PR](https://github.com/sindresorhus/pupa/pull/25).

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/pupa/issues/17#issuecomment-1019078196.

**Pull request closed without merging**
